draw_set_font(credit_font_header);
draw_set_color(c_white);
draw_text(x,y,"Thanks for Playing.");
draw_text(x,y+100,"Team Longship");
draw_set_font(credit_font_body);
draw_text(x,y+180,list[| 0]);
draw_text(x,y+210,list[| 1]);
draw_text(x,y+240,list[| 2]);
draw_text(x,y+270,list[| 3]);
draw_text(x,y+300,list[| 4]);
draw_text(x,y+330,list[| 5]);
draw_text(x,y+360,list[| 6]);
draw_set_font(credit_font_header);
draw_text(x,y+450,"Special Thanks");
draw_set_font(credit_font_body);
draw_text(x,y+530,"Mark Brown (GMTK)");
draw_text(x,y+560,"Tarlicus (Best Mod)");
